# Generated by Django 4.0.2 on 2022-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_avatar_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='../static/core/default_avatar.png', upload_to='images/avatars'),
        ),
    ]
