# Generated by Django 4.0.2 on 2022-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='wardrobe.Accessory'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='outerwear',
            field=models.ManyToManyField(blank=True, to='wardrobe.Outerwear'),
        ),
    ]
